name: Debug Actions

on:
  push:
    branches: [ main ]


jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Load Config to ENV
        id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true
    
      - name: Update Charts
        env: 
          VERSION: ${{ steps.meta.outputs.labels["org.opencontainers.image.version"] }}
          REPO: ${{ steps.dotenv.outputs.repo }}
          REGISTRY: ${{ steps.dotenv.outputs.registry }}/
          NAME: ${{ steps.dotenv.outputs.project_name }}
          HOST: ${{ steps.dotenv.outputs.project_host }}
        run: |
          sed -i "s/PROJECT_NAME/$NAME/g" chart/values.yaml 
          sed -i "s/REPO/$REPO/g" chart/values.yaml
          sed -i "s/PROJECT_HOST/$HOST/g" chart/values.yaml
          sed -i "s/REGISTRY/$REGISTRY/g" chart/values.yaml
          cat chart/values.yaml

          sed -i "s/PROJECT_NAME/$NAME/g" chart/Chart.yaml
          sed -i "s/RELEASE_VERSION/$VERSION/g" chart/Chart.yaml
          cat Chart.yaml

      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          STEPS: ${{ toJson(steps)}}
        run: | 
          echo "$GITHUB_CONTEXT" \
          echo "$STEPS"
